# Generated by Django 4.1.6 on 2023-03-09 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(default='small', on_delete=django.db.models.deletion.CASCADE, to='products_app.product'),
            preserve_default=False,
        ),
    ]
