# Generated by Django 4.1.6 on 2023-03-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
