# Generated by Django 4.1.6 on 2023-03-09 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0004_alter_cartitem_product_alter_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offerproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.productsizeandprice')),
            ],
        ),
    ]
