# Generated by Django 4.1.6 on 2023-03-09 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0005_offerproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products_app.product'),
        ),
    ]
